package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"math/big"
	"os"
	"strings"
)

var giantMap = make(map[string]string)
var babyMap = make(map[string]string)

// missingParametersError prints usage information when the program is invoked without the required input-file argument.
func missingParametersError() {
	fmt.Println("ERROR: Parameters missing!")
	fmt.Println("HELP:")
	fmt.Println("./dl-efficient <filename for input>")
}

// setupCLI validates the command-line arguments and returns the input filename.
func setupCLI() string {
	if len(os.Args) < 2 {
		missingParametersError()
		os.Exit(1)
	}
	inputFile := os.Args[1]
	return inputFile
}

// getInputText returns the full contents of the named file as a string.
func getInputText(inputText string) string {
	dataBytes, err := ioutil.ReadAll(file)
	if err != nil {
		log.Fatal(err)
	}
	return string(dataBytes)
}

// Function to return the values from the input string
func getParameters(inputFile string) (*big.Int, *big.Int, *big.Int) {

	P := new(big.Int)
	G := new(big.Int)
	H := new(big.Int)

	fileText := getInputText(inputFile)
	fileText = fileText[2 : len(fileText)-2]
	fileTextSplit := strings.Split(fileText, ",")
	PText := fileTextSplit[0]
	GText := fileTextSplit[1]
	HText := fileTextSplit[2]

	P.SetString(PText, 10)
	G.SetString(GText, 10)
	H.SetString(HText, 10)

	return P, G, H
}

func getM(P *big.Int) *big.Int {
	M := new(big.Int)
	M.Sqrt(P)
	return M
}

// We are calculating the possible values of G^y mod P where 0<=y<limit and storing them in a map with key being y
func buildBabyTable(G, H, P, limit *big.Int) map[string]string {
	one := big.NewInt(1)
	baby := make(map[string]string)

	// value = H * G^r (mod P), starting at r = 0 where value = H.
	value := new(big.Int).Mod(H, P)
	r := new(big.Int)
	for r.SetInt64(0); r.Cmp(limit) < 0; r.Add(r, one) {
		baby[value.String()] = r.String()
		value.Mul(value, G)
		value.Mod(value, P)
	}
	return baby
}

// Multiply G^M every loop with itself for q times where 0<=q<limit and check if the value is in the baby table, if it is then we can calculate x = q*M - r where r is the value from the baby table and return x
func babyStepGiantStep(G, M, P, limit *big.Int, baby map[string]string) (*big.Int, bool) {
	one := big.NewInt(1)

	gm := new(big.Int).Exp(G, M, P) // giant stride G^M
	giant := big.NewInt(1)          // (G^M)^0, the q = 0 value
	q := new(big.Int)
	for q.SetInt64(0); q.Cmp(limit) < 0; q.Add(q, one) {
		if rStr, ok := baby[giant.String()]; ok {
			r := new(big.Int)
			r.SetString(rStr, 10)
			x := new(big.Int).Mul(q, M)
			x.Sub(x, r) // x = q*M - r
			return x, true
		}
		giant.Mul(giant, gm)
		giant.Mod(giant, P)
	}
	return nil, false
}

//Main Function
func main() {
	inputFile := setupCLI()

	P, G, H := getParameters(inputFile)

	// M is the step size; limit is the number of baby/giant steps to take.
	// With M = floor(sqrt(P)) and limit = floor(P/M)+1, the two ranges of
	// ~sqrt(P) steps cover every exponent in [0, P).
	M := getM(P)
	limit := new(big.Int).Div(P, M)
	limit.Add(limit, big.NewInt(1))

	baby := buildBabyTable(G, H, P, limit)

	x, found := babyStepGiantStep(G, M, P, limit, baby)
	if !found {
		fmt.Fprintln(os.Stderr,
			"no discrete logarithm found: H is not in the subgroup generated by G, or x >= P")
		os.Exit(1)
	}
	fmt.Println(x)
}

